#ifndef ATLAS_CORE_ATLAS_JOINT_NUM_H
#define ATLAS_CORE_ATLAS_JOINT_NUM_H

typedef enum {
    ATLAS_JOINT_NUM_1,
    ATLAS_JOINT_NUM_2,
    ATLAS_JOINT_NUM_3,
    ATLAS_JOINT_NUM_4,
    ATLAS_JOINT_NUM_5,
    ATLAS_JOINT_NUM_6,
    ATLAS_JOINT_NUM,
} atlas_joint_num_t;

#endif // ATLAS_CORE_ATLAS_JOINT_NUM_H