#ifndef COMMON_NOTIFY_H
#define COMMON_NOTIFY_H

typedef enum {
    SYSTEM_NOTIFY_JOINTS_READY = (1 << 0),
    SYSTEM_NOTIFY_PACKET_READY = (1 << 1),
    SYSTEM_NOTIFY_RETRY_TIMER = (1 << 2),
    SYSTEM_NOTIFY_ALL =
        (SYSTEM_NOTIFY_JOINTS_READY | SYSTEM_NOTIFY_PACKET_READY | SYSTEM_NOTIFY_RETRY_TIMER),
} system_notify_t;

typedef enum {
    JOINT_NOTIFY_DELTA_TIMER = (1 << 0),
    JOINT_NOTIFY_PWM_PULSE = (1 << 1),
    JOINT_NOTIFY_ALL = (JOINT_NOTIFY_DELTA_TIMER | JOINT_NOTIFY_PWM_PULSE),
} joint_notify_t;

typedef enum {
    JOINTS_NOTIFY_JOINT_READY =
        ((1 << ATLAS_JOINT_NUM_1) | (1 << ATLAS_JOINT_NUM_2) | (1 << ATLAS_JOINT_NUM_3) |
         (1 << ATLAS_JOINT_NUM_4) | (1 << ATLAS_JOINT_NUM_5) | (1 << ATLAS_JOINT_NUM_6)),
    JOINTS_NOTIFY_DELTA_TIMER = (1 << 6),
    JOINTS_NOTIFY_RETRY_TIMER = (1 << 7),
    JOINTS_NOTIFY_ALL =
        (JOINTS_NOTIFY_JOINT_READY | JOINTS_NOTIFY_DELTA_TIMER | JOINTS_NOTIFY_RETRY_TIMER),
} joints_notify_t;

typedef enum {
    PACKET_NOTIFY_ROB_PACKET_READY = (1 << 0),
    PACKET_NOTIFY_ALL = (PACKET_NOTIFY_ROB_PACKET_READY),
} packet_notify_t;

#endif // COMMON_NOTIFY_H